FROM ubuntu:latest
LABEL com.tsmks.source.image.authors="cmink@tsmks.com"
ENV DEBIAN_FRONTEND noninteractive

RUN apt update -y && apt install -y
RUN apt install texlive-full -y
RUN apt install texlive-latex-extra -y

WORKDIR /data
VOLUME ["/data"]
